version: '3.5'

services:
  db:
    image: postgres:10.0
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    environment:
      - RAILS_DB_URL_DEV=postgresql://postgres:password@db/vuetest_development
      - RAILS_DB_URL_TEST=postgresql://postgres:password@db/vuetest_test
    build: .
    command: /bin/sh -c "rm -f /vuetest/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/vuetest
      - /vuetest/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
