default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Jake

development:
  <<: *default
  url: <%= ENV['RAILS_DB_URL_DEV'] || 'postgresql://localhost/vuetest_development' %>

test:
  <<: *default
  url: <%= ENV['RAILS_DB_URL_TEST'] || 'postgresql://localhost/vuetest_test' %>

production:
  <<: *default
  url: <%= ENV['RAILS_DB_URL'] %>
